### ISSUE TITLE
关于LISA数据集的制作

### ISSUE THREAD

**Issue by qhykwsw** [jinfagang/TrafficLightsDetection#13]
我注意到data文件夹下的trainval.txt和test.txt是由LISA数据集中的dayClip1、dayClip10、dayClip11、dayClip12、dayClip13这五个文件夹里的图片随机组成，再分为4:1的训练和测试集。但是这5个数据集的总图片数是4108张，而数据集有3285+822=4107张，这是故意的么？
还有按照你readme中生成labels的方式，gen_all_labels.sh生成的dayClipx--xxxxx.txt都是空的文件。如何变成class_index x_min y_min x_max y_max的形式呢？

还有“Place first model into ./models/VGGNet/LISA/SSD_414x125 Place second model into ./models/VGGNet ”，这里写颠倒了。

**Comment by lucasjinreal** [comment]
@qhykwsw Have a look our new traffic light detection model, with yolov3 and mobilenet support, achieve stoa speed and accuracy... it's almost the most advanced detection for now.
http://strangeai.pro/aicodes_detail.html?id=26

**Comment by qhykwsw** [comment]
我已经关注并购买了，但是你们目前发布在gitlab上的源码并没有提供数据集制作和训练测试脚本，请尽快更新，谢啦。

**Comment by lucasjinreal** [comment]
@qhykwsw 👌
