### ISSUE TITLE
couldn't open caffemodel

### ISSUE THREAD

**Issue by sunian6183** [jinfagang/TrafficLightsDetection#14]
when I run the command below:
python ssd_detection.py
,I got the error:
Could not open file models/VGGNet/LISA/SSD_414x125/VGG_LISA_SSD_414x125_iter_120000.caffemodel
Segmentation fault (core dumped)

**Comment by lucasjinreal** [comment]
You can check new model from http://manaai.cn

Yolov3 is the much more accurate and fast trafficlight detector.

**Comment by sunian6183** [comment]
> You can check new model from http://manaai.cn
> 
> Yolov3 is the much more accurate and fast trafficlight detector.

thank you,but I don't want to change cuda ,mine is 8.0. I just want to test.
